title: YunoHost documentation
author:
  name: YunoHost contributors
  email: 'yunohost@yunohost.org'
metadata:
    description: 'The multi-language documentation for the selfhosting system YunoHost'

